name: hungry_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  provider: ^6.1.5
  intl: ^0.20.2

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # الحزمة الصحيحة لتوليد ملفات الترجمة
  intl_utils: ^2.8.2

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/3dModel/
    - assets/banner/
    - assets/detail/
    - assets/icon/
    - assets/logo/
    - assets/splash/
    - assets/test/
    - assets/lottie/
    - assets/translaitions/